<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class LabTestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $labTests = [
            [
                'name' => 'Complete Blood Count',
                'description' => 'Measures components of blood including WBC, RBC, and platelets.',
                'category' => 'Hematology',
                'code' => 'CBC001',
                'requires_fasting' => false,
                'preparation_instructions' => 'No preparation needed.',
                'sample_type' => 'Blood',
                'normal_range' => 'WBC: 4.5–11.0, RBC: 4.5–5.9',
            ],
            [
                'name' => 'Fasting Blood Sugar',
                'description' => 'Checks glucose levels after fasting.',
                'category' => 'Biochemistry',
                'code' => 'FBS002',
                'requires_fasting' => true,
                'preparation_instructions' => 'Fast for at least 8 hours.',
                'sample_type' => 'Blood',
                'normal_range' => '70–99 mg/dL',
            ],
            [
                'name' => 'Urinalysis',
                'description' => 'Detects substances in the urine.',
                'category' => 'Urine Test',
                'code' => 'UA003',
                'requires_fasting' => false,
                'preparation_instructions' => 'Midstream clean catch.',
                'sample_type' => 'Urine',
                'normal_range' => 'pH: 4.5–8.0',
            ],
            [
                'name' => 'Lipid Profile',
                'description' => 'Measures cholesterol and triglycerides.',
                'category' => 'Biochemistry',
                'code' => 'LP004',
                'requires_fasting' => true,
                'preparation_instructions' => 'Do not eat 9–12 hours before test.',
                'sample_type' => 'Blood',
                'normal_range' => 'LDL < 100 mg/dL',
            ],
            [
                'name' => 'Liver Function Test',
                'description' => 'Assesses liver enzyme levels.',
                'category' => 'Biochemistry',
                'code' => 'LFT005',
                'requires_fasting' => false,
                'preparation_instructions' => 'Avoid alcohol 24 hours prior.',
                'sample_type' => 'Blood',
                'normal_range' => 'ALT: 7–56 U/L',
            ],
            [
                'name' => 'Thyroid Panel',
                'description' => 'Checks thyroid hormone levels.',
                'category' => 'Endocrinology',
                'code' => 'TP006',
                'requires_fasting' => false,
                'preparation_instructions' => 'Take medication after test if applicable.',
                'sample_type' => 'Blood',
                'normal_range' => 'TSH: 0.4–4.0 mIU/L',
            ],
            [
                'name' => 'Electrolyte Panel',
                'description' => 'Measures levels of electrolytes.',
                'category' => 'Biochemistry',
                'code' => 'EP007',
                'requires_fasting' => false,
                'preparation_instructions' => 'Stay hydrated.',
                'sample_type' => 'Blood',
                'normal_range' => 'Na+: 135–145 mmol/L',
            ],
            [
                'name' => 'Vitamin D Test',
                'description' => 'Checks Vitamin D levels.',
                'category' => 'Nutrition',
                'code' => 'VD008',
                'requires_fasting' => false,
                'preparation_instructions' => 'No supplements for 24 hours.',
                'sample_type' => 'Blood',
                'normal_range' => '20–50 ng/mL',
            ],
            [
                'name' => 'HbA1c',
                'description' => 'Measures average blood sugar over 3 months.',
                'category' => 'Biochemistry',
                'code' => 'A1C009',
                'requires_fasting' => false,
                'preparation_instructions' => 'No preparation needed.',
                'sample_type' => 'Blood',
                'normal_range' => '<5.7%',
            ],
            [
                'name' => 'HIV Test',
                'description' => 'Detects HIV antibodies.',
                'category' => 'Infectious Disease',
                'code' => 'HIV010',
                'requires_fasting' => false,
                'preparation_instructions' => 'Consent required.',
                'sample_type' => 'Blood',
                'normal_range' => 'Negative',
            ],
            [
                'name' => 'COVID-19 PCR',
                'description' => 'Detects active COVID-19 infection.',
                'category' => 'Infectious Disease',
                'code' => 'COV011',
                'requires_fasting' => false,
                'preparation_instructions' => 'Avoid nasal spray for 24 hours.',
                'sample_type' => 'Nasal Swab',
                'normal_range' => 'Negative',
            ],
            [
                'name' => 'Pregnancy Test',
                'description' => 'Detects hCG hormone.',
                'category' => 'Hormonal',
                'code' => 'PT012',
                'requires_fasting' => false,
                'preparation_instructions' => 'First morning urine preferred.',
                'sample_type' => 'Urine',
                'normal_range' => 'Negative',
            ],
            [
                'name' => 'Malaria Parasite Test',
                'description' => 'Detects malaria parasites.',
                'category' => 'Parasitology',
                'code' => 'MP013',
                'requires_fasting' => false,
                'preparation_instructions' => 'Avoid antimalarial drugs prior.',
                'sample_type' => 'Blood',
                'normal_range' => 'Negative',
            ],
            [
                'name' => 'Sputum Culture',
                'description' => 'Detects bacteria in lungs.',
                'category' => 'Microbiology',
                'code' => 'SC014',
                'requires_fasting' => false,
                'preparation_instructions' => 'Collect early morning sample.',
                'sample_type' => 'Sputum',
                'normal_range' => 'No growth',
            ],
            [
                'name' => 'Stool Test',
                'description' => 'Detects parasites or blood in stool.',
                'category' => 'Parasitology',
                'code' => 'ST015',
                'requires_fasting' => false,
                'preparation_instructions' => 'No antibiotics 48 hours prior.',
                'sample_type' => 'Stool',
                'normal_range' => 'Normal flora',
            ],
            [
                'name' => 'ESR',
                'description' => 'Measures inflammation.',
                'category' => 'Hematology',
                'code' => 'ESR016',
                'requires_fasting' => false,
                'preparation_instructions' => 'No exercise before test.',
                'sample_type' => 'Blood',
                'normal_range' => '0–20 mm/hr',
            ],
            [
                'name' => 'Blood Urea Nitrogen (BUN)',
                'description' => 'Measures kidney function.',
                'category' => 'Biochemistry',
                'code' => 'BUN017',
                'requires_fasting' => false,
                'preparation_instructions' => 'Hydrate before the test.',
                'sample_type' => 'Blood',
                'normal_range' => '7–20 mg/dL',
            ],
            [
                'name' => 'Creatinine Test',
                'description' => 'Assesses kidney function.',
                'category' => 'Biochemistry',
                'code' => 'CR018',
                'requires_fasting' => false,
                'preparation_instructions' => 'Avoid meat 24 hours prior.',
                'sample_type' => 'Blood',
                'normal_range' => '0.6–1.2 mg/dL',
            ],
            [
                'name' => 'Calcium Test',
                'description' => 'Measures calcium levels.',
                'category' => 'Biochemistry',
                'code' => 'CA019',
                'requires_fasting' => false,
                'preparation_instructions' => 'Avoid calcium supplements.',
                'sample_type' => 'Blood',
                'normal_range' => '8.6–10.2 mg/dL',
            ],
            [
                'name' => 'Prostate-Specific Antigen (PSA)',
                'description' => 'Detects prostate issues.',
                'category' => 'Cancer Screening',
                'code' => 'PSA020',
                'requires_fasting' => false,
                'preparation_instructions' => 'Avoid ejaculation 24 hours before test.',
                'sample_type' => 'Blood',
                'normal_range' => '0–4 ng/mL',
            ],
            [
                'name' => 'C-Reactive Protein (CRP)',
                'description' => 'Detects inflammation or infection.',
                'category' => 'Immunology',
                'code' => 'CRP021',
                'requires_fasting' => false,
                'preparation_instructions' => 'No special preparation needed.',
                'sample_type' => 'Blood',
                'normal_range' => '<3.0 mg/L',
            ],
            [
                'name' => 'Erythropoietin Test',
                'description' => 'Measures levels of erythropoietin hormone.',
                'category' => 'Endocrinology',
                'code' => 'EPO022',
                'requires_fasting' => false,
                'preparation_instructions' => 'No special preparation needed.',
                'sample_type' => 'Blood',
                'normal_range' => '4–24 mIU/mL',
            ],
            [
                'name' => 'Serum Iron',
                'description' => 'Measures amount of iron in blood.',
                'category' => 'Biochemistry',
                'code' => 'SI023',
                'requires_fasting' => true,
                'preparation_instructions' => 'Fast for 8 hours before test.',
                'sample_type' => 'Blood',
                'normal_range' => '60–170 µg/dL',
            ],
            [
                'name' => 'Ferritin',
                'description' => 'Measures iron storage in the body.',
                'category' => 'Biochemistry',
                'code' => 'FER024',
                'requires_fasting' => false,
                'preparation_instructions' => 'No special preparation needed.',
                'sample_type' => 'Blood',
                'normal_range' => '20–500 ng/mL',
            ],
            [
                'name' => 'Troponin Test',
                'description' => 'Detects heart muscle damage.',
                'category' => 'Cardiology',
                'code' => 'TRP025',
                'requires_fasting' => false,
                'preparation_instructions' => 'No preparation needed.',
                'sample_type' => 'Blood',
                'normal_range' => '<0.04 ng/mL',
            ],
            [
                'name' => 'Cortisol Test',
                'description' => 'Measures cortisol hormone levels.',
                'category' => 'Endocrinology',
                'code' => 'COR026',
                'requires_fasting' => false,
                'preparation_instructions' => 'Sample usually collected in the morning.',
                'sample_type' => 'Blood',
                'normal_range' => '6–23 µg/dL (morning)',
            ],
            [
                'name' => 'Insulin Test',
                'description' => 'Evaluates insulin levels.',
                'category' => 'Endocrinology',
                'code' => 'INS027',
                'requires_fasting' => true,
                'preparation_instructions' => 'Fast for 8–10 hours.',
                'sample_type' => 'Blood',
                'normal_range' => '2–25 µIU/mL',
            ],
            [
                'name' => 'D-Dimer Test',
                'description' => 'Detects blood clotting problems.',
                'category' => 'Hematology',
                'code' => 'DDM028',
                'requires_fasting' => false,
                'preparation_instructions' => 'No preparation needed.',
                'sample_type' => 'Blood',
                'normal_range' => '<0.5 µg/mL',
            ],
            [
                'name' => 'Vitamin B12 Test',
                'description' => 'Measures levels of Vitamin B12.',
                'category' => 'Nutrition',
                'code' => 'VB1229',
                'requires_fasting' => false,
                'preparation_instructions' => 'Avoid supplements before test.',
                'sample_type' => 'Blood',
                'normal_range' => '200–900 pg/mL',
            ],
            [
                'name' => 'Folate Test',
                'description' => 'Measures folate levels in blood.',
                'category' => 'Nutrition',
                'code' => 'FOL030',
                'requires_fasting' => false,
                'preparation_instructions' => 'Avoid multivitamins before test.',
                'sample_type' => 'Blood',
                'normal_range' => '>3.0 ng/mL',
            ],
            [
                'name' => 'Rheumatoid Factor (RF)',
                'description' => 'Checks for rheumatoid arthritis.',
                'category' => 'Immunology',
                'code' => 'RF031',
                'requires_fasting' => false,
                'preparation_instructions' => 'No preparation needed.',
                'sample_type' => 'Blood',
                'normal_range' => '<14 IU/mL',
            ],
            [
                'name' => 'ANA (Antinuclear Antibody)',
                'description' => 'Detects autoimmune disorders.',
                'category' => 'Immunology',
                'code' => 'ANA032',
                'requires_fasting' => false,
                'preparation_instructions' => 'No special preparation.',
                'sample_type' => 'Blood',
                'normal_range' => 'Negative',
            ],
            [
                'name' => 'Lead Blood Test',
                'description' => 'Measures lead levels in blood.',
                'category' => 'Toxicology',
                'code' => 'LBT033',
                'requires_fasting' => false,
                'preparation_instructions' => 'Avoid seafood 48 hours before test.',
                'sample_type' => 'Blood',
                'normal_range' => '<5 µg/dL',
            ],
            [
                'name' => 'Amylase Test',
                'description' => 'Measures enzyme related to pancreas.',
                'category' => 'Biochemistry',
                'code' => 'AML034',
                'requires_fasting' => false,
                'preparation_instructions' => 'No alcohol 24 hours before test.',
                'sample_type' => 'Blood',
                'normal_range' => '30–110 U/L',
            ],
            [
                'name' => 'Lipase Test',
                'description' => 'Used to diagnose pancreatitis.',
                'category' => 'Biochemistry',
                'code' => 'LIP035',
                'requires_fasting' => false,
                'preparation_instructions' => 'Avoid fatty meals before test.',
                'sample_type' => 'Blood',
                'normal_range' => '0–160 U/L',
            ],
            [
                'name' => 'Monospot Test',
                'description' => 'Detects Epstein-Barr virus.',
                'category' => 'Infectious Disease',
                'code' => 'MON036',
                'requires_fasting' => false,
                'preparation_instructions' => 'No special preparation.',
                'sample_type' => 'Blood',
                'normal_range' => 'Negative',
            ],
            [
                'name' => 'Chlamydia Test',
                'description' => 'Detects Chlamydia infection.',
                'category' => 'Infectious Disease',
                'code' => 'CHL037',
                'requires_fasting' => false,
                'preparation_instructions' => 'Avoid urination for 1 hour prior.',
                'sample_type' => 'Urine',
                'normal_range' => 'Negative',
            ],
            [
                'name' => 'Gonorrhea Test',
                'description' => 'Detects Gonorrhea infection.',
                'category' => 'Infectious Disease',
                'code' => 'GON038',
                'requires_fasting' => false,
                'preparation_instructions' => 'Avoid urination for 1 hour prior.',
                'sample_type' => 'Urine',
                'normal_range' => 'Negative',
            ],
            [
                'name' => 'Hepatitis B Surface Antigen (HBsAg)',
                'description' => 'Screens for Hepatitis B infection.',
                'category' => 'Infectious Disease',
                'code' => 'HBV039',
                'requires_fasting' => false,
                'preparation_instructions' => 'Consent may be required.',
                'sample_type' => 'Blood',
                'normal_range' => 'Negative',
            ],
            [
                'name' => 'Helicobacter Pylori Antigen',
                'description' => 'Detects H. pylori infection.',
                'category' => 'Microbiology',
                'code' => 'HPY040',
                'requires_fasting' => false,
                'preparation_instructions' => 'No antibiotics or PPIs for 2 weeks.',
                'sample_type' => 'Stool',
                'normal_range' => 'Negative',
            ],            
        ];

        foreach ($labTests as &$test) {
            $test['is_active'] = true;
            $test['created_at'] = now();
            $test['updated_at'] = now();
        }

        DB::table('lab_test')->insert($labTests);
    }
}
